[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
dirs = "5.0.1"
ratatui = { version = "0.23.0", features = ["all-widgets"] }

[dependencies.rune-core]
path = "../core"
